# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(850, 530)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Individuation = QtWidgets.QGroupBox(Dialog)
        self.Individuation.setObjectName("Individuation")
        self.formLayout = QtWidgets.QFormLayout(self.Individuation)
        self.formLayout.setObjectName("formLayout")
        self.theme_text = QtWidgets.QLabel(self.Individuation)
        self.theme_text.setObjectName("theme_text")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.theme_text)
        self.theme = QtWidgets.QComboBox(self.Individuation)
        self.theme.setObjectName("theme")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.theme)
        self.language_text = QtWidgets.QLabel(self.Individuation)
        self.language_text.setObjectName("language_text")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.language_text)
        self.language = QtWidgets.QComboBox(self.Individuation)
        self.language.setObjectName("language")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.language)
        self.horizontalLayout.addWidget(self.Individuation)
        self.Update = QtWidgets.QGroupBox(Dialog)
        self.Update.setObjectName("Update")
        self.formLayout_2 = QtWidgets.QFormLayout(self.Update)
        self.formLayout_2.setObjectName("formLayout_2")
        self.c_v_text = QtWidgets.QLabel(self.Update)
        self.c_v_text.setObjectName("c_v_text")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.c_v_text)
        self.c_v = QtWidgets.QLabel(self.Update)
        self.c_v.setObjectName("c_v")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.c_v)
        self.l_v_text = QtWidgets.QLabel(self.Update)
        self.l_v_text.setObjectName("l_v_text")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.l_v_text)
        self.l_v = QtWidgets.QLabel(self.Update)
        self.l_v.setObjectName("l_v")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.l_v)
        self.check_n_v = QtWidgets.QPushButton(self.Update)
        self.check_n_v.setObjectName("check_n_v")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.check_n_v)
        self.horizontalLayout.addWidget(self.Update)
        self.Other = QtWidgets.QGroupBox(Dialog)
        self.Other.setObjectName("Other")
        self.formLayout_3 = QtWidgets.QFormLayout(self.Other)
        self.formLayout_3.setObjectName("formLayout_3")
        self.clear_cache = QtWidgets.QPushButton(self.Other)
        self.clear_cache.setObjectName("clear_cache")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.clear_cache)
        self.horizontalLayout.addWidget(self.Other)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Individuation.setTitle(_translate("Dialog", "Individuation"))
        self.theme_text.setText(_translate("Dialog", "theme"))
        self.language_text.setText(_translate("Dialog", "language"))
        self.Update.setTitle(_translate("Dialog", "Update"))
        self.c_v_text.setText(_translate("Dialog", "Current version"))
        self.c_v.setText(_translate("Dialog", "TextLabel"))
        self.l_v_text.setText(_translate("Dialog", "Latest version"))
        self.l_v.setText(_translate("Dialog", "TextLabel"))
        self.check_n_v.setText(_translate("Dialog", "Check the new version"))
        self.Other.setTitle(_translate("Dialog", "Other"))
        self.clear_cache.setText(_translate("Dialog", "ClearCache"))
