# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(841, 465)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.new_addon = QtWidgets.QPushButton(self.layoutWidget)
        self.new_addon.setObjectName("new_addon")
        self.verticalLayout.addWidget(self.new_addon)
        self.new_mod = QtWidgets.QPushButton(self.layoutWidget)
        self.new_mod.setObjectName("new_mod")
        self.verticalLayout.addWidget(self.new_mod)
        self.open = QtWidgets.QPushButton(self.layoutWidget)
        self.open.setObjectName("open")
        self.verticalLayout.addWidget(self.open)
        self.setting = QtWidgets.QPushButton(self.layoutWidget)
        self.setting.setObjectName("setting")
        self.verticalLayout.addWidget(self.setting)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.recent = QtWidgets.QGroupBox(self.splitter)
        self.recent.setObjectName("recent")
        self.gridLayout = QtWidgets.QGridLayout(self.recent)
        self.gridLayout.setObjectName("gridLayout")
        self.recent_list = QtWidgets.QListWidget(self.recent)
        self.recent_list.setObjectName("recent_list")
        self.gridLayout.addWidget(self.recent_list, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 841, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.new_addon.setText(_translate("MainWindow", "PushButton"))
        self.new_mod.setText(_translate("MainWindow", "PushButton"))
        self.open.setText(_translate("MainWindow", "PushButton"))
        self.setting.setText(_translate("MainWindow", "PushButton"))
        self.recent.setTitle(_translate("MainWindow", "GroupBox"))
