# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(841, 465)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.img = QtWidgets.QLabel(self.centralwidget)
        self.img.setText("")
        self.img.setObjectName("img")
        self.verticalLayout_2.addWidget(self.img)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.new_addon = QtWidgets.QPushButton(self.layoutWidget)
        self.new_addon.setObjectName("new_addon")
        self.verticalLayout.addWidget(self.new_addon)
        self.new_mod = QtWidgets.QPushButton(self.layoutWidget)
        self.new_mod.setObjectName("new_mod")
        self.verticalLayout.addWidget(self.new_mod)
        self.open = QtWidgets.QPushButton(self.layoutWidget)
        self.open.setObjectName("open")
        self.verticalLayout.addWidget(self.open)
        self.setting = QtWidgets.QPushButton(self.layoutWidget)
        self.setting.setObjectName("setting")
        self.verticalLayout.addWidget(self.setting)
        self.horizontalLayout.addWidget(self.splitter)
        self.notice_box = QtWidgets.QGroupBox(self.centralwidget)
        self.notice_box.setObjectName("notice_box")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.notice_box)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.notice_list = QtWidgets.QListWidget(self.notice_box)
        self.notice_list.setObjectName("notice_list")
        self.horizontalLayout_2.addWidget(self.notice_list)
        self.horizontalLayout.addWidget(self.notice_box)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 841, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.new_addon.setText(_translate("MainWindow", "bedrock"))
        self.new_mod.setText(_translate("MainWindow", "java"))
        self.open.setText(_translate("MainWindow", "open"))
        self.setting.setText(_translate("MainWindow", "setting"))
        self.notice_box.setTitle(_translate("MainWindow", "notice"))
